### ISSUE TITLE
Division by zero error on latest version

### ISSUE THREAD

**Issue by johnwbaxter** [nystudio107/craft3-imageoptimize#252] opened 2021-02-08 10:59 UTC
We have just updated our site to 1.6.21 and we are now seeing internal server errors on some existing pages (we're doing this on our dev site, not the live site btw)

In the logs we see:

2021-02-08 10:52:02 [-][148090][af77008254b715259471b53370b75f40][error][yii\base\ErrorException:2] yii\base\ErrorException: Division by zero in /srv/users/xxxxxxx/apps/xxxxxxxx/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php:485

- Plugin version: 1.6.21
- Craft version: 3.6.4.1

**Comment by khalwat** [comment] 2021-02-08 18:16
So that's this line: https://github.com/nystudio107/craft-imageoptimize/blob/v1/src/services/OptimizedImages.php#L485

```
            $aspectRatio = (int)$variant['aspectRatioX'] / (int)$variant['aspectRatioY'];
```

Can you check your settings for the field in question to see why the `aspectRatioY` might be 0?

I'm not seeing anything in the change logs that looks like it could affect this, so I'm not sure the update to the latest version was the issue.

**Comment by johnwbaxter** [comment] 2021-02-09 09:18
Hi Andrew, it says that the jpeg variants don't exist. But, if I click on the link below each variant size, it takes me straight to the variant, so they do exist?

**Comment by khalwat** [comment] 2021-02-09 15:56
Sounds like there was an error generating the variant, can you get any details from the logs?

**Comment by johnwbaxter** [comment] 2021-02-09 16:08
Nothing in web.log of any interest other than when it starts doing the division by zero issues!

**Comment by khalwat** [comment] 2021-02-09 16:11
Can you check your queue.log and console.log ?

Easiest to delete all logs, then reproduce the issue, so the logs are as small as possible.

**Comment by johnwbaxter** [comment] 2021-02-09 16:12
So, if I delete the existing logs now, and then, do what to generate the log data that would be of use? View front end entries, or save backend entries? Or both?

**Comment by johnwbaxter** [comment] 2021-02-09 16:14
No errors in the existing queue.log.

**Comment by khalwat** [comment] 2021-02-09 16:16
Let's arrange a time to do a video conference and have a look at this together. Ping me on Discord at your leisure.

**Comment by johnwbaxter** [comment] 2021-02-09 16:23
Yeah sure, does this time tomorrow suit you?

**Comment by khalwat** [comment] 2021-02-10 21:54
Fixed in https://github.com/nystudio107/craft-imageoptimize/releases/tag/1.6.22

**Closed as completed by khalwat** 2021-02-10 21:54 UTC
Labels: bug

**Comment by martin-coded** [comment] 2023-04-21 08:37
I think I also have an edge case. There is an image with dimensions of 3178px x 1862px and the error is Division by zero

```
2023-04-21 04:54:18 [queue.INFO] [nystudio107\imageoptimize\services\OptimizedImages::shouldCreateVariants] Matched '*' wildcard  {"memory":36774944} 
2023-04-21 04:54:18 [queue.INFO] [nystudio107\imageoptimize\services\OptimizedImages::addVariantImageToModel] URL created: /assets/images/article/_760x18_crop_center-center_60_line/369271/More-Button-on-Google-Chrome.jpg {"memory":36779232} 
2023-04-21 04:54:18 [queue.INFO] [nystudio107\imageoptimize\services\OptimizedImages::generatePlaceholders] generatePlaceholders for: nystudio107\imageoptimize\models\OptimizedImage Object
(
    [_events:yii\base\Component:private] => Array
        (
        )

    [_eventWildcards:yii\base\Component:private] => Array
        (
        )

    [_behaviors:yii\base\Component:private] => Array
        (
        )

    [_errors:yii\base\Model:private] => 
    [_validators:yii\base\Model:private] => 
    [_scenario:yii\base\Model:private] => default
    [optimizedImageUrls] => Array
        (
            [760] => /assets/images/article/_760x18_crop_center-center_60_line/369271/More-Button-on-Google-Chrome.jpg
        )

    [optimizedWebPImageUrls] => Array
        (
            [760] => /assets/images/article/_760x18_crop_center-center_60_line/369271/More-Button-on-Google-Chrome.jpg.webp
        )

    [variantSourceWidths] => Array
        (
            [0] => 760
        )

    [variantHeights] => Array
        (
            [760] => 18
        )

    [focalPoint] => Array
        (
            [x] => 0.5
            [y] => 0.5
        )

    [originalImageWidth] => 1914
    [originalImageHeight] => 46
    [placeholder] => 
    [placeholderSvg] => 
    [colorPalette] => Array
        (
        )

    [lightness] => 0
    [placeholderWidth] => 760
    [placeholderHeight] => 18
    [stickyErrors] => Array
        (
        )

)
 {"memory":36784008} 
2023-04-21 04:54:18 [queue.INFO] [nystudio107\imageoptimize\services\Placeholder::createTempPlaceholderImage] Creating temporary placeholder image for asset {"memory":36784440} 
2023-04-21 04:54:18 [queue.INFO] [nystudio107\imageoptimize\services\Placeholder::generatePlaceholderImage] Generating placeholder image for asset {"memory":36790624} 
2023-04-21 04:54:18 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [76551] Optimizing images in Article Images (attempt: 1, pid: 7) - Error (time: 943.751s): Division by zero {"memory":36802880} 
2023-04-21 04:54:18 [queue.ERROR] [DivisionByZeroError] DivisionByZeroError: Division by zero in /usr/local/apache2/htdocs/vendor/craftcms/cms/src/image/Raster.php:326
Stack trace:
#0 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(294): craft\image\Raster->scaleAndCrop(16, 0, true, Array)
#1 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(94): nystudio107\imageoptimize\services\Placeholder->createImageFromPath('/usr/local/apac...', 16, 0, 50, Array)
#2 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(467): nystudio107\imageoptimize\services\Placeholder->generatePlaceholderImage('/usr/local/apac...', 41.608695652174, Array)
#3 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(576): nystudio107\imageoptimize\services\OptimizedImages->generatePlaceholders(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), 41.608695652174)
#4 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(146): nystudio107\imageoptimize\services\OptimizedImages->addVariantImageToModel(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), Object(craft\models\ImageTransform), Array, 41.608695652174)
#5 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(281): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel(Object(craft\elements\Asset), Array, Object(nystudio107\imageoptimize\models\OptimizedImage), false)
#6 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/jobs/ResaveOptimizedImages.php(113): nystudio107\imageoptimize\services\OptimizedImages->updateOptimizedImageFieldData(Object(nystudio107\imageoptimize\fields\OptimizedImages), Object(craft\elements\Asset), false)
#7 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/Queue.php(246): nystudio107\imageoptimize\jobs\ResaveOptimizedImages->execute(Object(craft\queue\Queue))
#8 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(76551, 'O:52:"nystudio1...', 300, 1)
#9 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(183): yii\queue\cli\Queue->handleMessage(76551, 'O:52:"nystudio1...', 300, 1)
#10 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(158): craft\queue\Queue->executeJob()
#11 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#12 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/cli/Queue.php(114): call_user_func(Object(Closure), Object(Closure))
#13 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(156): yii\queue\cli\Queue->runWorker(Object(Closure))
#14 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#15 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/controllers/QueueController.php(103): craft\controllers\QueueController->actionRun()
#16 [internal function]: craft\controllers\QueueController->actionRetry()
#17 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#19 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('retry', Array)
#20 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('queue/retry', Array)
#21 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(627): craft\web\Application->runAction('queue/retry', Array)
#22 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /usr/local/apache2/htdocs/web/index.php(12): yii\base\Application->run()
#25 {main} {"memory":36803096,"exception":"[object] (DivisionByZeroError(code: 0): Division by zero at /usr/local/apache2/htdocs/vendor/craftcms/cms/src/image/Raster.php:326)"} 
2023-04-21 04:54:18 [queue.ERROR] [DivisionByZeroError] DivisionByZeroError: Division by zero in /usr/local/apache2/htdocs/vendor/craftcms/cms/src/image/Raster.php:326
Stack trace:
#0 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(294): craft\image\Raster->scaleAndCrop(16, 0, true, Array)
#1 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/Placeholder.php(94): nystudio107\imageoptimize\services\Placeholder->createImageFromPath('/usr/local/apac...', 16, 0, 50, Array)
#2 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(467): nystudio107\imageoptimize\services\Placeholder->generatePlaceholderImage('/usr/local/apac...', 41.608695652174, Array)
#3 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(576): nystudio107\imageoptimize\services\OptimizedImages->generatePlaceholders(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), 41.608695652174)
#4 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(146): nystudio107\imageoptimize\services\OptimizedImages->addVariantImageToModel(Object(craft\elements\Asset), Object(nystudio107\imageoptimize\models\OptimizedImage), Object(craft\models\ImageTransform), Array, 41.608695652174)
#5 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/services/OptimizedImages.php(281): nystudio107\imageoptimize\services\OptimizedImages->populateOptimizedImageModel(Object(craft\elements\Asset), Array, Object(nystudio107\imageoptimize\models\OptimizedImage), false)
#6 /usr/local/apache2/htdocs/vendor/nystudio107/craft-imageoptimize/src/jobs/ResaveOptimizedImages.php(113): nystudio107\imageoptimize\services\OptimizedImages->updateOptimizedImageFieldData(Object(nystudio107\imageoptimize\fields\OptimizedImages), Object(craft\elements\Asset), false)
#7 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/Queue.php(246): nystudio107\imageoptimize\jobs\ResaveOptimizedImages->execute(Object(craft\queue\Queue))
#8 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage(76551, 'O:52:"nystudio1...', 300, 1)
#9 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(183): yii\queue\cli\Queue->handleMessage(76551, 'O:52:"nystudio1...', 300, 1)
#10 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(158): craft\queue\Queue->executeJob()
#11 [internal function]: craft\queue\Queue->craft\queue\{closure}(Object(Closure))
#12 /usr/local/apache2/htdocs/vendor/yiisoft/yii2-queue/src/cli/Queue.php(114): call_user_func(Object(Closure), Object(Closure))
#13 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/queue/Queue.php(156): yii\queue\cli\Queue->runWorker(Object(Closure))
#14 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/controllers/QueueController.php(82): craft\queue\Queue->run()
#15 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/controllers/QueueController.php(103): craft\controllers\QueueController->actionRun()
#16 [internal function]: craft\controllers\QueueController->actionRetry()
#17 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#19 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('retry', Array)
#20 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('queue/retry', Array)
#21 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(627): craft\web\Application->runAction('queue/retry', Array)
#22 /usr/local/apache2/htdocs/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#23 /usr/local/apache2/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#24 /usr/local/apache2/htdocs/web/index.php(12): yii\base\Application->run()
#25 {main} {"memory":36803912,"exception":"[object] (DivisionByZeroError(code: 0): Division by zero at /usr/local/apache2/htdocs/vendor/craftcms/cms/src/image/Raster.php:326)"} 
```
