### ISSUE TITLE
Thumbnails of image files in the assets index are not displayed

### ISSUE THREAD

**Issue by mihob** [nystudio107/craft3-imageoptimize#359] opened 2022-10-26 11:58 UTC
### Describe the bug

Since version 4.3.0 of craft (the index pages have been reworked) the thumbnails in the assets index are no longer displayed when ImageOptimize is enabled. Only a generic icon of the file type is displayed. When Image Optimize is disabled, everything works as expected.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Assets"

### Expected behaviour
Thumbnails of image files should be displayed

### Screenshots

![asset-index](https://user-images.githubusercontent.com/48485580/198020025-88022b27-03d5-43af-b331-dda8d2cdf055.png)

### Versions
- Plugin version: 4.0.2
- Craft version: Craft Pro 4.3.0

**Comment by khalwat** [comment] 2022-10-26 16:28
I will have a look; sounds like they changed something with regards to image transforms.

**Comment by mihob** [comment] 2022-10-26 20:13
Yes, if I see it correctly, the bug does not only affect the asset index, at the moment no images are output at all.

**Comment by mihob** [comment] 2022-10-27 08:21
Any news on this?

**Comment by mikewink** [comment] 2022-10-27 08:28
I can confirm that issue. I ran into it after updating to Craft 4.3.0. All the images in the CP and frontend are gone. Disabling ImageOptimize brought back the images in the CP and the ones not optimized by the plugin.

Having a look at the changelog.md, there are two tickets ([9622](https://github.com/craftcms/cms/discussions/9622), [11970](https://github.com/craftcms/cms/discussions/11970)) directly tied to transforms.

**Comment by janhenckens** [comment] 2022-10-27 10:05
Downgrading to 4.2.8 also fixed the issue for us

**Comment by thijskaspers** [comment] 2022-10-27 11:00
Same here, Craft 4.3.0 + ImageOptimize breaks all image transforms (CP and front-end).

**Comment by brandonkelly** [comment] 2022-10-27 14:29
This was due to an unintended breaking change in 4.3.0, where `Asset::getUrl()` was respecting plugins which set `$event->url = null`, as ImageOptimize is doing (https://github.com/craftcms/cms/commit/5c837e43ec2742571a1940f0245d4789bb33ace1).

Fixed for the next Craft 4 release (https://github.com/craftcms/cms/commit/3f00b8d3efb7e8ee1b0a2e20018c1d802c0b2ed8).

**Comment by brandonkelly** [comment] 2022-10-27 20:06
Craft 4.3.1 has been released with the fix for ImageOptimize.

**Closed as completed** 2022-11-15 21:25 UTC
Labels: bug
