### ISSUE TITLE
[4.0.0-beta.3] Stuck queue task: transforms not being generated when set to 'auto'

### ISSUE THREAD

**Issue by Nellyaa** [nystudio107/craft3-imageoptimize#329] opened 2022-04-22 15:30 UTC
### Describe the bug
When you create an imageoptimize field with transforms set to 'auto', and attach that to an asset volume, image transforms aren't getting created and the queue task is stuck. Uploading new images to that volume won't get anything generated.
When setting the transforms to 'png' or 'jpg' this doesn't happen.

### To reproduce
Steps to reproduce the behaviour:
1. Create imageoptimize field with a transform set to 'auto'
2. Attach field to an asset volume
3. Observe stuck queue job

### Expected behaviour

Queue doesn't get stuck and generates image transforms accordingly

### Versions
- Plugin version: ImageOptimize 4.0.0-beta.3
- Craft version: Craft 4 beta.4

**Comment by JeanLucEsser** [comment] 2022-05-11 07:46
Same issue here.

**Comment by carolineboeykens** [comment] 2022-05-12 14:18
Same here!

**Comment by khalwat** [comment] 2022-05-17 14:08
Will be addressed shortly.

**Comment by simonkuran** [comment] 2022-06-07 06:27
Any ETA on this fix? The bug is really slowing down my development.

**Comment by curtismorte** [comment] 2022-06-07 21:15
We're facing this issue as well.

I don't think this is a direct issue with the Image Optimizer plugin though. I have traced down the issue to Craft's `ImageTransformer` class recursively calling itself until the queue hits a time out.

When calling `getTransformUrl()` for the [transformMethod](https://github.com/nystudio107/craft-imageoptimize/blob/develop/src/services/OptimizedImages.php#L546), you can eventually trace the logic down to [this place](https://github.com/craftcms/cms/blob/develop/src/imagetransforms/ImageTransformer.php#L78).

The problem is `getTransformUrl()` returns ` $this->ensureTransformUrlByIndexModel()`, but `$this->ensureTransformUrlByIndexModel` calls `getTransformUrl()` again. And you're stuck in a loop. I haven't investigated this further, but I wanted to bring it to your attention.

**Comment by khalwat** [comment] 2022-06-07 22:23
Thanks @curtismorte yep it's a little more involved than just a bug in ImageOptimize, but I'm hoping to resolve it this week.

**Comment by curtismorte** [comment] 2022-06-10 23:31
**I've tracked this issue down further.**

I set up a small test to identify the source of the problems. I have:
1. Created a new filesystem using the AWS S3 Plugin.
2. Created a new volume that specifies the filesystem from step 1 as the upload and transform filesystem.
3. Created a new image optimize field, where is produces 3 variants, with image formats all being different (png, jpg, auto).
4. Uploaded a new image to the volume through assets in the control panel
5. Use the console command `nitro craft image-optimize/optimize/create-asset $ID --force` to force the optimizations to run
6. Inspect the console logs to figure out what's going on

The only variant that gives any problems is the variant with the image format being `auto`. The problem is that Craft's `ImageTransformer:getTransformIndex()` receives a `$transform` parameter
with the format field set to any empty string. All the other variants have defined fields.

```php
        if ($transform->format === null) {
            // A generated auto-transform will have its format set to null, but the filename will be populated.
            $query->andWhere(['format' => null]);
        } else {
            $query->andWhere(['format' => $transform->format]);
        }
```
> When Craft goes to make the query above, the query doesn't return and results, and thus you get stuck in a loop.

So I backtracked through the code which took me to [populateOptimizedImageModel()](https://github.com/nystudio107/craft-imageoptimize/blob/develop/src/services/OptimizedImages.php#L81). Upon inspection,
I found that any `$variant` with format defined (`$variant['format']`) would successfully generate all the image
optimizations. Which led me to try the following:

```php
/**
     * @param Asset          $asset
     * @param array          $variants
     * @param OptimizedImage $model
     * @param boolean        $force
     */
    public function populateOptimizedImageModel(Asset $asset, $variants, OptimizedImage $model, $force = false)
    {
        Craft::beginProfile('populateOptimizedImageModel', __METHOD__);
        $settings = ImageOptimize::$plugin->getSettings();
        // Empty our the optimized image URLs
        $model->optimizedImageUrls = [];
        $model->optimizedWebPImageUrls = [];
        $model->variantSourceWidths = [];
        $model->placeholderWidth = 0;
        $model->placeholderHeight = 0;
        $model->stickyErrors = [];

        foreach ($variants as $variant) {
            $retinaSizes = ['1'];
            
            # ADDED THIS
            $variant['format'] = empty($variant['format']) ? $asset->getExtension() : $variant['format'];
            ...
        }

        // If no image variants were created, populate it with the image itself
        if (empty($model->optimizedImageUrls)) {
            $finalFormat = $asset->getExtension();
            if (Image::canManipulateAsImage($finalFormat)
                && Image::canManipulateAsImage($finalFormat)
                && $asset->height > 0) {
                $variant = [
                    'width' => $asset->width,
                    'useAspectRatio' => false,
                    'aspectRatioX' => $asset->width,
                    'aspectRatioY' => $asset->height,
                    'retinaSizes' => ['1'],
                    'quality' => 0,
                    # ADDED THIS
                    'format' => $finalFormat
                ];
                ...
            } else {
                ...
            }
        }
        Craft::endProfile('populateOptimizedImageModel', __METHOD__);
    }
```

> Defining the variant's format based on the images format seemed to do the trick.

**Comment by curtismorte** [comment] 2022-06-11 00:23
Also, you'll likely need to update your asset indexes.

My development environment has 17,000 indexes, and my staging environment only has 5600. My suspicion is the looping was creating excess indexes. This was caused by me manually running console commands to force Image Optimizer to update assets.

**Comment by khalwat** [comment] 2022-06-17 11:04
Perfect, thanks for tracking it down so well!

**Comment by khalwat** [comment] 2022-06-25 04:48
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/3598ec1e50fc3fb377fa4fc23708ce4369830339

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-image-optimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2022-06-25 04:48 UTC
Labels: bug

**Comment by simonkuran** [comment] 2022-06-26 08:14
With 4.0.0-beta.4 installed, when I run `php craft image-optimize/optimize/create` for a volume I'm now getting a `Could not create transform for: FPO resource image - Final format: 1 - Element extension: jpg - canManipulateAsImage: 1` error for each variant with its "Image Format" set to "auto".

Happy to open a new issue if it's helpful, but I'm assuming this is closely related.

**Comment by khalwat** [comment] 2022-06-27 01:33
@curtismorte wrote:

> Defining the variant's format based on the images format seemed to do the trick

So in your fix, this line:
```php
            # ADDED THIS
            $variant['format'] = empty($variant['format']) ? $asset->getExtension() : $variant['format'];
```
doesn't really do anything, because we do this just after:

```php
                $finalFormat = empty($variant['format']) ? $asset->getExtension() : $variant['format'];
```

...but what makes the critical difference is this part of your fix:

```php
                    # ADDED THIS
                    'format' => $finalFormat
```

...because apparently for some reason, whatever changes were made internally causes it to call `getTransformUrl()` recursively if the format is omitted from the transform. Probably it's a regression, but either way, I really appreciate your help in tracking it down!

**Comment by khalwat** [comment] 2022-06-27 01:37
@simonkuran wrote:

> With 4.0.0-beta.4 installed, when I run `php craft image-optimize/optimize/create` for a volume I'm now getting a `Could not create transform for: FPO resource image - Final format: 1 - Element extension: jpg - canManipulateAsImage: 1` error for each variant with its "Image Format" set to "auto".
> 
> Happy to open a new issue if it's helpful, but I'm assuming this is closely related.

Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/eead9224c8c8a9e978c367f2d78d5152c809f32f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-image-optimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`

**Comment by simonkuran** [comment] 2022-06-27 12:47
That fixed it, thanks!

**Comment by khalwat** [comment] 2022-06-27 12:48
Great! Thanks to @curtismorte as well!

**Comment by curtismorte** [comment] 2022-07-02 00:18
Happy to see this one! Thanks @khalwat.
