### ISSUE TITLE
Transforms don't get deleted on remote volumes

### ISSUE THREAD

**Issue by JensvdHeydt** [nystudio107/craft3-imageoptimize#341] opened 2022-05-30 09:26 UTC
### Describe the bug
I'm using DigitalOcean Spaces Volume v1.1.3 and when I delete an asset some directories and files don't get removed from the remote volume. It seems to be the webp variants that image optimize creates and their respective directories. The original file gets deleted by craft. There's a comment in the executed funtion in Optimize.php, line 397: "// Only do this for local Craft transforms". Maybe that's the issue?

### To reproduce
Steps to reproduce the behaviour:
1. When using a remote volume upload an asset and let craft create optimized variants
2. Delete the asset
3. Transform variants (webp) don't get deleted from remote volume.

### Expected behaviour
Remote volume should not be ignored when deleting transform variant files.

### Screenshots

<img width="940" alt="Bildschirmfoto 2022-05-30 um 11 25 28" src="https://user-images.githubusercontent.com/19750185/170961677-f264f5fe-7fa0-4d60-9d9c-ffd228b0cfbc.png">

### Versions
- Plugin version: 1.6.44
- Craft version: 3.7.43

**Comment by JensvdHeydt** [comment] 2022-06-14 15:21
@khalwat is this issue something you would consider as a bug? It would be wonderful if you could give me a short feedback. Otherwise I would have to find other ways of fixing this issue with my own event handlers.

**Comment by khalwat** [comment] 2022-06-14 15:27
i think it is likely a bug. I'll be looking into it!

**Comment by khalwat** [comment] 2022-06-27 04:33
We've tried to reproduce this, but are unable to -- could it perhaps be something specific to Digital Ocean Spaces? ImageOptimize doesn't actually do anything any different here than regular old Craft transforms.

So I'd expect the same behavior if you did a Craft transform in your templates, and then deleted the original image.

**Comment by JensvdHeydt** [comment] 2022-06-28 09:11
Hi @khalwat,

thanks for the feedback. I'll verify if the bug also exists using craft transforms. I'll get back to you.

**Comment by JensvdHeydt** [comment] 2022-06-28 11:09
@khalwat, I've tested with an ordinary craft transform and the generated assets don't get deleted on digital ocean. Could you point me in the right direction how I would be able to solve this issue, maybe with my own plugin? I guess there's an event I could listen for?

**Comment by JensvdHeydt** [comment] 2022-07-06 16:13
@khalwat I tested this once more with a local volume and found the same behaviour:

- ImageOptimize creates 3 image variants for my PNG with different image sizes
- It also creates 3 WEBP named something like "__original name__.png.webp" variants 
- When I delete the image from the local asset volume it deletes the PNG transforms of different size but leaves the *.png.WEBPs that were also created

Did this work at your end?

**Comment by khalwat** [comment] 2022-07-06 19:28
I will give it a whirl, but I've not encountered this before, no.

**Comment by JensvdHeydt** [comment] 2022-07-07 12:42
@khalwat 

I've debugged some more and found something interesting:

- If I edit my Image Optimizer field and set the image format to JPG for example, all my transforms get deleted correctly
- If I set the Image Optimizer field's image format to "auto" the webp - files remain in undeleted

I think the problem is in Optimize.php, line 799, function cleanupImageVariants. $fileformat is always empty, when I am using "auto" as image format. Therefore the function to delete the transforms is never fully executed
<img width="765" alt="Bildschirmfoto 2022-07-07 um 14 39 52" src="https://user-images.githubusercontent.com/19750185/177775742-4e83af07-7e6b-4d14-8258-19e7903a3f3c.png">

**Comment by curtismorte** [comment] 2022-07-07 15:22
Could this potentially be related to the issues in #329?

Specifically, the issue there was caused by the format not being set when the image format is "auto".

**Comment by JensvdHeydt** [comment] 2022-07-07 15:31
Yes, I think it's related or at least has a similar cause. If the format is empty the cleanup function never actually deletes transform files, @curtismorte 

empty($activeImageVariantCreators[$fileFormat]) is always false in that case.

**Comment by khalwat** [comment] 2022-07-11 17:04
@JensvdHeydt nice sleuthing! Sorry for being slow to respond, on a holiday, but let me roll out a fix.

**Comment by khalwat** [comment] 2022-07-11 17:17
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/d71a87a4f5c43a2602a5d5f7dba3506a370e41c0 & https://github.com/nystudio107/craft-imageoptimize/commit/9061074ecd36c1c28ae49b81d8281bc1516eed68

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.48”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`

**Comment by JensvdHeydt** [comment] 2022-07-12 13:44
@khalwat thanks! I'll give it a spin.

**Comment by JensvdHeydt** [comment] 2022-07-12 14:28
@khalwat Just tested it on a local and remote volume. Both worked. Great work and never mind those "slow" responses on a holiday!

**Comment by JensvdHeydt** [comment] 2022-07-13 13:56
Hi @khalwat,
one last thing that we noticed: There seems to be a problem when using uppercase letters in the file extension, like ".PNG" or ".JPG".  In that case, transforms don't get deleted. Maybe you could implement strtolower before comparing the filetypes?

**Comment by khalwat** [comment] 2022-07-13 19:53
@JensvdHeydt Just addressed that now

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.48”,
```
Then do a `composer clear-cache && composer update`


Craft CMS 4:

…..

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.2”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment] 2022-07-14 19:28
@JensvdHeydt lmk if that fix does it for you, and I will close this out and cut a release.

**Comment by JensvdHeydt** [comment] 2022-07-15 08:37
@khalwat Just tested it with a remote volume. Works like it should! Thanks again.

**Closed as completed** 2022-07-17 20:26 UTC
Labels: bug, need info
