### ISSUE TITLE
WebP Image variants not generated for jpgs whose file extension is all caps

### ISSUE THREAD

**Issue by richardcalahan** [nystudio107/craft3-imageoptimize#277] opened 2021-05-04 15:04 UTC
### Describe the bug
Very odd one. I've tested in multiple environments against several images. Each time, if the image file extension is all caps, ie, image.JPG or image.JPEG, webp variants are skipped. Simply changing the name to image.jpg or image.jpeg and reuploading will allow proper variant creation.  

### To reproduce
Steps to reproduce the behaviour:
1. Upload an asset to an imageOptimized volume with a file extension in all caps, ie, image.JPG
2. Check for webp variants in the image optimize preview
3. See broken image for all webp variants

### Expected behaviour
Webp variants are viewable in the preview after the background queue finishes

### Versions
- Plugin version: 1.6.33
- Craft version: 3.6.12.1

**Comment by khalwat** [comment] 2021-05-07 13:56
That's pretty interesting... will fix thx!

**Comment by juban** [comment] 2021-05-11 11:37
Hi @khalwat 

I can confirm that too.
Any image file extensions using caps (JPG, PNG, etc...) seems to be ignored from the webp processing.

**Comment by khalwat** [comment] 2021-05-11 17:15
Fixed in https://github.com/nystudio107/craft-imageoptimize/commit/4822043b08501bebcba2deb360f7088f66b09ebd

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop as 1.6.34”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2021-05-11 17:15 UTC
Labels: bug
