### ISSUE TITLE
Unable to select Aspect Ratio, Add or Delete variants - 4.0.0-beta3

### ISSUE THREAD

**Issue by zizther** [nystudio107/craft3-imageoptimize#344] opened 2022-06-10 00:24 UTC
### Describe the bug
When creating an image optimize field it is not possible to select a `Aspect Ratio`, it does not change from the default 16:9
I am also not able to add or delete any of the default variants, even when managing via the config file.

No error messages show in the console or log files.

### Versions
- Plugin version: 4.0.0-beta.3
- Craft version: 4.0.4
- PHP 8.1

**Comment by michtio** [comment] 2022-06-10 12:17
@zizther this is a duplicate of #325 , you can change the things when you save the field and then edit again. ( for now )

**Comment by zizther** [comment] 2022-06-10 13:20
@michtio thanks for the heads up on this.

**Comment by khalwat** [comment] 2022-06-28 03:54
Addressed in: https://github.com/nystudio107/craft-imageoptimize/commit/bb9b7df9bd5266d08b9690b7b06e49c6011fe25f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-imageoptimize": "dev-develop-v4 as 4.0.0-beta.4”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2022-06-28 03:54 UTC
Labels: bug
